name: Docker Image CI

on:
  #release:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

      
    - uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        GIT_COMMIT: $(git rev-parse HEAD)
      with:
        name: jfcal/causality-assessment-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        snapshot: true
        tags: "latest"
        workdir: .
        buildargs: GIT_COMMIT
